services:
  postgres:
    image: postgres:15-alpine
    container_name: bedrud_postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=Testtest12345
      - POSTGRES_DB=test
    ports:
      - "5444:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      bedrud-network:
        ipv4_address: 172.16.240.10

  dbgate:
    image: dbgate/dbgate:latest
    container_name: bedrud_dbgate
    restart: unless-stopped
    environment:
      DBGATE_CONNECTIONS: |
        [
          {
            "engine": "postgres@dbgate-plugin-postgres",
            "name": "Bedrud Database",
            "server": "postgres",
            "port": 5432,
            "user": "test",
            "password": "Testtest12345",
            "database": "test"
          }
        ]

      DBGATE_ADMIN_PASSWORD: admin123
      DBGATE_PORT: 3000
      DBGATE_PUBLIC_URL: http://localhost:3000
      DBGATE_AUTH_DISABLED: "true"
      DBGATE_ALLOW_ANONYMOUS: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./data/dbgate:/root/.dbgate
    depends_on:
      - postgres
    networks:
      bedrud-network:
        ipv4_address: 172.16.240.11

  livekit:
    image: livekit/livekit-server:latest
    container_name: bedrud_livekit
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      - REDIS_ADDRESS=redis:6379
      - KEYS_TTL=48h
      - PORT=7880
      - BIND_INTERFACE=0.0.0.0
      - KEY=devkey
      - TURN_PORT=3478
      - RTC_NODE_IP=127.0.0.1
    depends_on:
      - redis
    volumes:
      - ./livekit.yaml:/config.yaml
    command: --config /config.yaml
    networks:
      bedrud-network:
        ipv4_address: 172.16.240.12

  redis:
    image: redis:6-alpine
    container_name: bedrud_redis
    ports:
      - "6379:6379"
    networks:
      bedrud-network:
        ipv4_address: 172.16.240.13

networks:
  bedrud-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.240.0/24
